### ISSUE TITLE
use with 'kubectl apply -k ...'

### ISSUE THREAD

**Issue by cameronkerrnz** [viaduct-ai/kustomize-sops#124]
Hello, I'm getting my feet wet with Kustomize and have started using the following pattern, now that kustomize is folded into kubectl:

```
kubectl apply -k ...
```

I want to apply this to use it with Kustomize-SOPS (I'm on Windows, but the teams I working with are on Mac and Linux too), but I can't find any documentation around how to get ksops integrated with kubectl.

Right now I'm assuming that this is not a workable option (because I would need to be able to specify --enable-alpha-plugins somehow), but I'm willing to help test and write some documentation that would enable people to use 'kubectl apply -k' with ksops.

I am playing with this currently (just learning SOPS at present, will have a look at KSOPS more tomorrow).

**Comment by devstein** [comment]
Hi @cameronkerrnz thanks for making an issue. To my knowledge (though admittedly I haven't checked since `kustomize` v4) it is not possible to use it directly with `kubectl apply -k`. 

The suggested pattern is 

```bash
kustomize build --enable_alpha_plugins  path/to/overlays | kubectl apply -f -
```

This builds the manifests with `kustomize` then applies the `stdout` (`-`) with `kubectl`
