### ISSUE TITLE
v4.1.3 uses new paths for ksops and kustomize which breaks ArgoCD Integration

### ISSUE THREAD

**Issue by jimmy-ungerman** [viaduct-ai/kustomize-sops#184]
It appears that v4.1.3 of the ksops image changed where the ksops and kustomize binaries from `/go/bin/ksops` and `go/bin/kustomzie` to `/usr/local/bin/ksops` and `/usr/local/bin/kustomize`.

This is making the current ArgoCD integration documentation for Kustomize and Helm incorrect. I'd be glad to edit it as I just fixed it!

**Comment by devstein** [comment]
@jimmy-ungerman Thanks for making an issue! Sorry for the breaking change. Is this [PR](https://github.com/viaduct-ai/kustomize-sops/pull/183/files) what you had in mind or do you want to preserve the old path `/go/bin/` path?

**Comment by muhlba91** [comment]
i ran into the same issue today, and it broke my ArgoCD integration since i pinned the ksops image to `v4`.
since the integration is documented by yourself, i believe introducing that change without a major version change or some cutover time/versions can result in others having their ArgoCD broken as well.

personally, i prefer `/usr/local/bin` for its consistency across multiple platform, and, in my opinion, the more "logical" place -although i understand this is a personal preference.

**Comment by devstein** [comment]
@jimmy-ungerman @muhlba91 Thanks for the input. I agree it should have been a part of a new major release. For now, I'm patching the new image to maintain backwards compatibility (https://github.com/viaduct-ai/kustomize-sops/pull/185), which I will remove in a future v5 release.
