### ISSUE TITLE
Brew package

### ISSUE THREAD

**Issue by qcastel** [viaduct-ai/kustomize-sops#61]
First, you may like to hear that we adopted Ksops as part of our deployment process. It is now use for deployment to prod but as well as deploying to our local environment :) 

The feedback I have from the engineers joining our team is that it's boilerplate to install ksops. The main reason they gave me is that they tried the documentation steps and it doesn't work.
Indeed, on mac, you need to setup Go properly so I have to add additional steps for them to complete the ksops installation.

Nevertheless, they all come back to me saying that a brew package would be so much nicer and I tend to agree.

Are you planning to deploy Ksops as a brew package? As we install kustomise using brew (https://kubernetes-sigs.github.io/kustomize/installation/homebrew/) would be nice to have ksops installed the same way.

**Comment by devstein** [comment]
@qcastel Thanks for making an issue and glad to hear you've adopted KSOPS! 

I haven't thought of installing the package via homebrew. I will look into it and let you know! It would definitely make the initial setup and upgrades easier.

**Comment by triThirty** [comment]
Hi @qcastel ,
I have met some problems when I tried to install ksops on my mac. I installed ksops according to READ.me step by step, but when I executed `kustomize build --enable_alpha_plugins`, it prompted `Error: loading generator plugins: plugin /Users/xxx/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so fails to load: plugin: not implemented` .
I read you said `Indeed, on mac, you need to setup Go properly so I have to add additional steps for them to complete the ksops installation.` , so could you please tell what steps I need to do to finish installing?

**Comment by qcastel** [comment]
@triThirty In my company, which is on mac os, we ask every engineer that has to setup ksops to add the following setup at the end of their zshrc:

```
export XDG_CONFIG_HOME=$HOME/.config
export GOPATH=/Users/$USER/go
export PATH=$GOPATH/bin:$PATH
```

**Comment by devstein** [comment]
Hi @qcastel, I looked into creating a Brew package for KSOPS, but it doesn't seem possible because setting up a `kustomize` plugin requires moving files into the `$XDG_CONFIG_HOME` directory, which Brew doesn't have permission to access by default.

As a substitute, I created a [script for downloading and installing the latest KSOPS exec plugin](https://github.com/viaduct-ai/kustomize-sops/pull/84). This makes setting up KSOPS a one-line command. The Exec plugin is functionally identical to the Go plugin, so it can be used interchangeably. The downsides of the Exec plugin are:

1. Non-helpful error messages. Unlike the Go plugin, kustomize swallows the errors for the Exec plugin, so the error messages can be cryptic 
2. Inconsistent kustomize versions. The KSOPS Go plugin is pinned to a specific kustomize version and fails loudly if it's built with a different version, so it's easy to test across many environments. The exec plugin uses whatever kustomize binary the user has installed, so it's on the user to make sure their kustomize version is compatible with the KSOPS exec plugin.


Below the script to download and install the latest KSOPS exec plugin. I also added it to the [README](https://github.com/viaduct-ai/kustomize-sops#remotely-download-the-latest-release).

```bash
# Verify the $XDG_CONFIG_HOME environment variable exists then run
source <(curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh)
```

I'm closing the issue because there is no clear path for creating KSOPS Brew package, but hope this script helps!
