### ISSUE TITLE
Problems with Docker image ("plugin was built with a different version of package golang.org/x/sys/unix")

### ISSUE THREAD

**Issue by larsks** [viaduct-ai/kustomize-sops#80]
I'm trying to run Ksops using the Docker image:

```
docker run -v $HOME:$HOME -w $PWD viaductoss/ksops kustomize build --enable_alpha_plugins
```

And this is throwing the error:

```
2020/12/16 16:05:29 Attempting plugin load from '/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so'
Error: loading generator plugins: plugin /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so fails to load: plugin.Open("/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops"): plugin was built with a different version of package golang.org/x/sys/unix
```

It looks like there may be build problems with the Docker image? I'm using the latest `v2` tagged image (`sha256:b9cae14e97b51181143bdd681fedbc1c6c5d402515ffc4d6d5f5875dfd072881`).

**Comment by devstein** [comment]
@larsks Thanks for making an issue and provide instructions for reproducing! 

Do you mind sharing the output of `kustomize version`?

**Comment by larsks** [comment]
Sure. It's whatever you've got in the docker image:

```
$ docker run docker.io/viaductoss/ksops:v2 kustomize version
{Version:v3.9.0+ksops.v2.3.0 GitCommit:v3@v3.9.0 BuildDate:2020-12-11T17:55:00Z GoOs:linux GoArch:amd64}
```

I seem to hit the same issue if I build the image myself from the `Dockerfile` in the repository.

**Comment by devstein** [comment]
@larsks The `v2.3.0` release was broken because `kustomize v3.9.0` is still in alpha and there is an outstanding issue that breaks kustomize plugins; however, this error is not related to your issue 😄 

The issue you are seeing is because kustomize go plugins require the plugin to be built on the same _system_ with the same _go version_ as kustomize itself. In this case, `kusomize` is built within the `golang` (ksops:v2) container, but `ksops` is built on your machine (the `$HOME` volume mount). 

There are two options:
1. Do not use the `docker run` and instead run `make kustomize && make install` in the root of this repo to set up `ksops` locally
2. Use the `ksops-exec` plugin instead of the original `go` plugin. This will work with the `docker run` workflow. You can read more in the [README](https://github.com/viaduct-ai/kustomize-sops#experimental-exec-plugin) and let me know if you have any questions!

**Comment by larsks** [comment]
@devstein thanks for the reply, but I think you may be mistaken about a couple of things.

> The issue you are seeing is because kustomize go plugins require the plugin to be built on the same system with the same go version as kustomize itself. In this case, kusomize is built within the golang (ksops:v2) container, but ksops is built on your machine (the $HOME volume mount).

1. I'm not building ksops on my local machine. I'm just running the image from docker hub. Nothing is being compiled or built at any point.
2. There is no ksops in my home directory.
3. Even if there were, it wouldn't matter: recall the the container runs as `root`, and I'm not mounting anything on `root`'s home directory (which is `/root` inside the container), so nothing in my `~/.config` would ever be found by `kustomize` inside the container.

This really looks like a problem with how the image is built.
